import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "What is the level of cyberattacks in the EU?",
  "subtitle": "As of 2024, on average 7.32% of enterprises in the EU experienced cyber attacks.",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url,target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.043,FALSE,,,,,,,,,,\nBelgium,BE,0.081,FALSE,,,,,,,,,,\nBulgaria,BG,0.045,FALSE,,,,,,,,,,\nCroatia,HR,0.089,FALSE,,,,,,,,,,\nCyprus,CY,0.050,FALSE,,,,,,,,,,\nCzechia,CZ,0.097,FALSE,,,,,,,,,,\nDenmark,DK,0.071,FALSE,,,,,,,,,,\nEstonia,EE,0.072,FALSE,,,,,,,,,,\nFinland,FI,0.148,FALSE,,,,,,,,,,\nFrance,FR,0.088,FALSE,,,,,,,,,,\nGermany,DE,0.089,FALSE,,,,,,,,,,\nGreece,EL,0.061,FALSE,,,,,,,,,,\nHungary,HU,0.051,FALSE,,,,,,,,,,\nIreland,IE,0.044,FALSE,,,,,,,,,,\nItaly,IT,0.058,FALSE,,,,,,,,,,\nLatvia,LV,0.063,FALSE,,,,,,,,,,\nLithuania,LT,0.052,FALSE,,,,,,,,,,\nLuxembourg,LU,0.061,FALSE,,,,,,,,,,\nMalta,MT,0.109,FALSE,,,,,,,,,,\nNetherlands,NL,0.096,FALSE,,,,,,,,,,\nPoland,PL,0.114,FALSE,,,,,,,,,,\nPortugal,PT,0.049,FALSE,,,,,,,,,,\nRomania,RO,0.119,FALSE,,,,,,,,,,\nSlovakia,SK,0.044,FALSE,,,,,,,,,,\nSlovenia,SI,0.045,FALSE,,,,,,,,,,\nSpain,ES,0.062,FALSE,,,,,,,,,,\nSweden,SE,0.075,FALSE,,,,,,,,,,\n",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.043,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.081,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.045,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.089,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.05,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.097,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.071,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.072,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.148,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.088,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.089,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.061,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.051,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.044,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.058,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.063,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.052,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.061,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.109,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.096,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.114,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.049,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.119,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.044,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.045,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.062,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.075,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url": "",
      "target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2025)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Categories for cyber attacks on enterprises are defined as the following: Disclosure of confidential data (due to intrusion, phishing, pharming, or actions by employees – intentional or unintentional) - Unavailability of ICT services (due to external attacks, hardware or software failures) - Destruction or corruption of data (due to malware, unauthorised access, hardware or software failures).",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/isoc_cisce_ic__custom_19759395/default/table",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of enterprises",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "What is the level of cyberattacks in the EU?",
    "subtitle": "As of 2024, on average 7.32% of enterprises in the EU experienced cyber attacks.",
    "textNoteDescription": "Note",
    "textNote": "Categories for cyber attacks on enterprises are defined as the following: Disclosure of confidential data (due to intrusion, phishing, pharming, or actions by employees – intentional or unintentional) - Unavailability of ICT services (due to external attacks, hardware or software failures) - Destruction or corruption of data (due to malware, unauthorised access, hardware or software failures).",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2025)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here"
  },
  "clusters": [],
  "colorScale": null
});